seed: 42

#data:
#  generator: independent_bernoulli
#  n: 1000
#  d: 8
#  params:
#    p: 0.5

# Esempio alternativo: binary chain
data:
   generator: binary_chain
   n: 1000
   d: 8
   params:
     epsilon: 0.15